version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app:cached

    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WATCHPACK_POLLING=true
